### ISSUE TITLE
Marshaler does not give an opportunity to indicate an error

### ISSUE THREAD

**Issue by excepttheweasel** [cloudfoundry-incubator/candiedyaml#11]
Consider:

```go
type Marshaler interface {
	MarshalYAML() (tag string, value interface{})
}
```

Then an example implementation:

```go
func (b *BinaryContainer) MarshalYAML() (tag string, value interface{}) {
	var buffer bytes.Buffer
	encoder := base64.NewEncoder(base64.StdEncoding, &buffer)
	_, err := encoder.Write(b.bytes)
	if err != nil {
		// Uh oh, what do! PANIC
	}
	encoder.Close()
	return ("", string(buffer.Bytes()))
}
```

A similar type in exists in https://github.com/go-yaml/yaml/blob/v2/yaml.go which allows for returning an error:

```go
type Marshaler interface {
	MarshalYAML() (interface{}, error)
}
```

Changing this would break the API, which you may not be comfortable with. Perhaps we could introduce an alternative Marshaler interface which allows returning an error?

**Comment by ematpl** [comment]
Thanks for the suggestion, @excepttheweasel. From my reading of the Encoder's [Encode method](https://github.com/cloudfoundry-incubator/candiedyaml/blob/master/encode.go#L82-L98) and the [recovery function](https://github.com/cloudfoundry-incubator/candiedyaml/blob/master/decode.go#L80-L98) it defers, it will attempt to recover from panics during marshaling and return them as errors, so it might actually be appropriate to panic in `MarshalYAML()` in an error case. It's kind of an exception-y flow, but I imagine it simplifies the marshaling logic. @fraenkel, can you confirm? Any other thoughts on this?

Thanks again,
Eric, CF Runtime Diego PM

**Comment by fraenkel** [comment]
The panic would work as a temporary solution. The proper solution is to support an error and have the library handle how errors are propagated within.

**Comment by fraenkel** [comment]
Fixed.
