### ISSUE TITLE
Move to cloudfoundry org

### ISSUE THREAD

**Issue by karlkfi** [cloudfoundry-incubator/candiedyaml#13]
Why is this still in incubator?

**Comment by emalm** [comment]
Hi, @karlkfi,

The `candiedyaml` library is now deprecated in favor of other YAML libraries such as [`gopkg.in/yaml.v2`](https://gopkg.in/yaml.v2) and is no longer under active development, so we'll instead move this repo to the [cloudfoundry-attic](https://github.com/cloudfoundry-attic) shortly.

Best,
Eric
