### ISSUE TITLE
Bug: interface{} map keys are not alphanumerically encoded

### ISSUE THREAD

**Issue by karlkfi** [cloudfoundry-incubator/candiedyaml#14]
Keys are alphanumerically encoded if the key type is known to be a string, otherwise order is the same as range order (occasionally random).

These tests that shows the following behavior:
- pass: "encodes map string keys in alphanumeric order"
- fails: "encodes map interface keys in alphanumeric order"

```
package candiedyaml

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("Marshal", func() {

	var iterations = 20

	It("encodes map string keys in alphanumeric order", func() {
		for i := 0; i < iterations; i++ {
			input := map[string]interface{}{
				"avg": 0.288,
				"hr": 63,
				"name": "Sammy Sosa",
			}

			output, err := Marshal(input)
			Expect(err).NotTo(HaveOccurred())

			Expect(string(output)).To(Equal(`avg: 0.288
hr: 63
name: Sammy Sosa
`))
		}

	})

	It("encodes map interface keys in alphanumeric order", func() {
		for i := 0; i < iterations; i++ {
			input := map[interface{}]interface{}{
				"avg": 0.288,
				"hr": 63,
				"name": "Sammy Sosa",
			}

			output, err := Marshal(input)
			Expect(err).NotTo(HaveOccurred())

			Expect(string(output)).To(Equal(`avg: 0.288
hr: 63
name: Sammy Sosa
`))
		}

	})

})
```

**Comment by karlkfi** [comment]
Perhaps a more frequently occurring use case is when the data is Unmarshaled into a `interface{}` and then Marshaled back to a string. Any maps in a `interface{}` have implicitly untyped keys.

**Comment by fraenkel** [comment]
Not sure why you think there is any order with a map.
Depending on the version of Go, the iteration through a map is random (https://golang.org/doc/go1.3#map).

**Comment by karlkfi** [comment]
Yes, I know. The problem is that the built-in json encoder alphabetizes keys. So if you're going back and forth between json and yaml it creates inconsistency. It's especially confusing that the output is different with `string` keys vs `interface{}` keys.

This bug was discovered when trying to use candiedyaml to replace go-yaml (which has alphabetized keys). See https://github.com/ghodss/yaml/pull/6 (a round-tripping wrapper to use json annotations).

**Comment by fraenkel** [comment]
This should now be fixed on master.

**Comment by karlkfi** [comment]
:tada:
