### ISSUE TITLE
Comment does not match code

### ISSUE THREAD

**Issue by sparkprime** [cloudfoundry-incubator/candiedyaml#21]
```
// objectInterface is like object but returns map[string]interface{}.
func (d *Decoder) mappingInterface() map[interface{}]interface{} {
```

And why not return map[string]interface{}?  That would make it possible to pass the result into json.Marshal

**Comment by ematpl** [comment]
Hi, @sparkprime,

YAML is a strict superset of JSON, and in particular YAML mappings can contain keys of scalar types other than strings, as described in the [Block Mappings section of the YAML 1.2 spec](http://www.yaml.org/spec/1.2/spec.html#id2798057). For example, the following Go program demonstrates that a YAML mapping can contain an integer, a string, and a floating-point key simultaneously:

```
package main

import (
	"fmt"

	"github.com/cloudfoundry-incubator/candiedyaml"
)

const document = `
---
1: a
"1": "AAAA!"
1.0: is-a-float
`

func main() {
	decoded := make(map[interface{}]interface{})
	err := candiedyaml.Unmarshal([]byte(document), &decoded)
	if err != nil {
		panic(err)
	}

	fmt.Printf("decoded: %#v\n", decoded)

	fmt.Printf("decoded[1]: %#v\n", decoded[int64(1)])
	fmt.Printf("decoded[\"1\"]: %#v\n", decoded["1"])
	fmt.Printf("decoded[1.0]: %#v\n", decoded[1.0])
}
```

When executed, the output of that program is the following:

```
decoded: map[interface {}]interface {}{1:"a", "1":"AAAA!", 1:"is-a-float"}
decoded[1]: "a"
decoded["1"]: "AAAA!"
decoded[1.0]: "is-a-float"
```

So in general you can't simply pass such a mapping to a JSON encoder without further restrictions on the type.

The comment that is out of alignment with the code seems to have come more or less from https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L951. I've corrected it, and the analogous one for `sequenceInterface`, in https://github.com/cloudfoundry-incubator/candiedyaml/commit/479485e9bfc69ee37d074b36ce36da5e4fba7941.

Thanks,
Eric Malm, CF Runtime Diego PM
