### ISSUE TITLE
libyaml out of date?

### ISSUE THREAD

**Issue by joshwget** [cloudfoundry-incubator/candiedyaml#22]
I might be wrong here, but I think #19 and #20 were both fixes in the portions of code transpiled from libyaml. If they were, then I think the fixes would be more appropriate in libyaml rather than on top of transpiled code. I also noticed that PyYAML and go-yaml don't have the same issues, so it's likely libyaml already has these fixes.

Is it possible that the transpiled version of libyaml is out of date?

**Comment by emalm** [comment]
Hi, @joshwget,

The `candiedyaml` library is now deprecated in favor of other YAML libraries such as [`gopkg.in/yaml.v2`](https://gopkg.in/yaml.v2) and is no longer under active development, so I'm closing out this issue.

Best,
Eric, Cloud Foundry Diego PM
