### ISSUE TITLE
panic when IsNil always called for strings matching nonPrintable.MatchString(s)

### ISSUE THREAD

**Issue by sayotte** [cloudfoundry-incubator/candiedyaml#24]
This snippet:

```
func (e *Encoder) emitString(tag string, v reflect.Value) {
    var style yaml_scalar_style_t
    s := v.String()

    if nonPrintable.MatchString(s) {
        _ = "breakpoint"
        e.emitBase64(tag, v)
        return
    }
```

 when confronted with a string that matches `"[^\t\n\r\u0020-\u007E\u0085\u00A0-\uD7FF\uE000-\uFFFD]"`, calls this snippet:

```
func (e *Encoder) emitBase64(tag string, v reflect.Value) {
    if v.IsNil() {
```

... which then panics with `call of reflect.Value.IsNil on string Value`.

An example string which provokes this: "\U00051274\U000ef396\U00036205\U00067e10\U000c7c55�\U00101957\U00078479\U000c10c7\U00090e68\U000d8799�\U00068f03\U0001e1ac\U0001820e\U000ef255\U000ade65\U000f067b\U000afcbd\U0004f4fd\U0004a633\U0007ed1f\U000e18eeấ\U000934bb\U000705e1\U0003dd50\U000ef68c\U0006c8ac\U000ead15\U000443a0�"

I discovered this while trying to use testing/quick to generate random instances of a struct which has a string field, when I then round-tripped to YAML and back. While it's certainly an edge-case, the strings are valid and provoke an inappropriate panic. More to the point, I can't use candiedyaml and testing/quick at the same time unless/until this is fixed, and I'd really like to use both.

**Comment by emalm** [comment]
Hi, @sayotte,

The `candiedyaml` library is now deprecated in favor of other YAML libraries such as [`gopkg.in/yaml.v2`](https://gopkg.in/yaml.v2) and is no longer under active development, so I'm closing out this issue.

Best,
Eric, Cloud Foundry Diego PM
