### ISSUE TITLE
Unvalid encoding of german characters

### ISSUE THREAD

**Issue by yulianedyalkova** [cloudfoundry-incubator/candiedyaml#25]
Calling the Marshal function with a string that has german characters returns invalid value. 
So for example calling it with "paßwörd" returns "pa\xDFw\xF=rd" when converted to string, which is in no valid encoding.

**Comment by emalm** [comment]
Hi, @yulianedyalkova,

The `candiedyaml` library is now deprecated in favor of other YAML libraries such as [`gopkg.in/yaml.v2`](https://gopkg.in/yaml.v2) and is no longer under active development, so I'm closing out this issue.

Best,
Eric, Cloud Foundry Diego PM
