### ISSUE TITLE
Allow for the existence of string "null", "NULL", "Null"

### ISSUE THREAD

**Issue by tdelacour** [cloudfoundry-incubator/candiedyaml#26]
At [https://github.com/cloudfoundry-incubator/candiedyaml/blob/4e924c79e32959414e8c7aaed6607176d8ee79c3/resolver.go#L55](url) these strings are made to represent NULL, the concept. The result is that a string that happens to be any of these words ends up getting replaced with the empty string upon parsing. It could be the case that the user actually just wants to keep the original string.

**Comment by emalm** [comment]
Hi, @tdelacour,

The `candiedyaml` library is now deprecated in favor of other YAML libraries such as [`gopkg.in/yaml.v2`](https://gopkg.in/yaml.v2) and is no longer under active development, so I'm closing out this issue.

Best,
Eric, Cloud Foundry Diego PM
